In [1]:
import pandas as pd
import numpy as np

In [2]:
np.random.seed(987654)

In [3]:
def generar_datos_sucios() -> pd.DataFrame:
    """
    Generar un DataFrame simulado con datos sucios para practicar limpieza.
    Contiene nulos, duplicados, nombres de columnas incorrectos y tipos erróneos.
    """
    datos = {
        ' ID Transaccion ': ['T001', 'T002', 'T003', 'T003', 'T005', np.nan, 'T007', 'T008'],
        'Fecha_Tx': ['2023-01-01', '02/01/2023', '2023-01-03', '2023-01-03', '2023-01-05', '2023-01-06', 'invalid_date', '2023-01-08'],
        'Cliente NOMB': ['  Juan Perez', 'Maria Lopez  ', 'carlos diaz', 'carlos diaz', 'Ana', 'Luis', 'Pedro', '  '],
        ' Monto $ ': ['$1,500.50', '2000', '$-350.00', '$-350.00', 'NaN', '450.75', '1000', '800.00'],
        'Categoria': ['Electrónica', 'Ropa', 'Ropa', 'Ropa', 'Alimentos', np.nan, 'Electrónica', 'Alimentos']
    }
    return pd.DataFrame(datos)

In [6]:
# 1. Generar e inspeccionar los datos iniciales
print("--- DATOS ORIGINALES (SUCIOS) ---")
df = generar_datos_sucios()
print(df)
print("\nTipos de datos originales:")
print(df.dtypes)
print("\n")

--- DATOS ORIGINALES (SUCIOS) ---
   ID Transaccion       Fecha_Tx   Cliente NOMB   Monto $     Categoria
0             T001    2023-01-01     Juan Perez  $1,500.50  Electrónica
1             T002    02/01/2023  Maria Lopez         2000         Ropa
2             T003    2023-01-03    carlos diaz   $-350.00         Ropa
3             T003    2023-01-03    carlos diaz   $-350.00         Ropa
4             T005    2023-01-05            Ana        NaN    Alimentos
5              NaN    2023-01-06           Luis     450.75          NaN
6             T007  invalid_date          Pedro       1000  Electrónica
7             T008    2023-01-08                    800.00    Alimentos

Tipos de datos originales:
 ID Transaccion     object
Fecha_Tx            object
Cliente NOMB        object
 Monto $            object
Categoria           object
dtype: object

In [14]:
def normalizar_columnas(dataframe: pd.DataFrame) -> pd.DataFrame:
    """
    Estandarizar nombres de columnas: minúsculas, sin espacios extra y con guiones bajos.
    """
    dataframe.columns = (
        dataframe.columns
        .str.strip()          # Eliminar espacios al inicio y final
        .str.lower()          # Convertir a minúsculas
        .str.replace(' ', '_')# Reemplazar espacios por guiones bajos
        .str.replace('$', '') # Eliminar caracteres especiales
    )
    return dataframe

print("--- 1. NORMALIZACIÓN DE COLUMNAS ---")
df = normalizar_columnas(df)
print("Nuevas columnas:", df.columns.tolist())
print("\n")

--- 1. NORMALIZACIÓN DE COLUMNAS ---
Nuevas columnas: ['id_transaccion', 'fecha_tx', 'cliente_nomb', 'monto_', 'categoria']

In [7]:
df = generar_datos_sucios()

In [8]:
df.columns

Index([' ID Transaccion ', 'Fecha_Tx', 'Cliente NOMB', ' Monto $ ',
       'Categoria'],
      dtype='object')

In [9]:
df.columns.str.strip()

Index(['ID Transaccion', 'Fecha_Tx', 'Cliente NOMB', 'Monto $', 'Categoria'], dtype='object')

In [12]:
df.columns.str.lower()

Index([' id transaccion ', 'fecha_tx', 'cliente nomb', ' monto $ ',
       'categoria'],
      dtype='object')

In [11]:
df.columns.str.replace(' ','_')

Index(['_ID_Transaccion_', 'Fecha_Tx', 'Cliente_NOMB', '_Monto_$_',
       'Categoria'],
      dtype='object')

In [13]:
df.columns.str.replace('$', '')

Index([' ID Transaccion ', 'Fecha_Tx', 'Cliente NOMB', ' Monto  ',
       'Categoria'],
      dtype='object')

In [17]:
df.head(10)

  id_transaccion      fecha_tx   cliente_nomb     monto_    categoria
0           T001    2023-01-01     Juan Perez  $1,500.50  Electrónica
1           T002    02/01/2023  Maria Lopez         2000         Ropa
2           T003    2023-01-03    carlos diaz   $-350.00         Ropa
3           T003    2023-01-03    carlos diaz   $-350.00         Ropa
4           T005    2023-01-05            Ana        NaN    Alimentos
5            NaN    2023-01-06           Luis     450.75          NaN
6           T007  invalid_date          Pedro       1000  Electrónica
7           T008    2023-01-08                    800.00    Alimentos

In [18]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7    False
dtype: bool

In [19]:
df[df.duplicated()]

  id_transaccion    fecha_tx cliente_nomb    monto_ categoria
3           T003  2023-01-03  carlos diaz  $-350.00      Ropa

In [20]:
# =============================================================================
# ST8: Manejo de duplicados
# =============================================================================
print("--- 2. MANEJO DE DUPLICADOS ---")
# Identificar duplicados
duplicados = df.duplicated().sum()
print(f"Filas duplicadas encontradas: {duplicados}")

--- 2. MANEJO DE DUPLICADOS ---
Filas duplicadas encontradas: 1

In [21]:
# Eliminar duplicados
df = df.drop_duplicates(keep='first').reset_index(drop=True)
print("DataFrame sin duplicados:")
print(df)
print("\n")

DataFrame sin duplicados:
  id_transaccion      fecha_tx   cliente_nomb     monto_    categoria
0           T001    2023-01-01     Juan Perez  $1,500.50  Electrónica
1           T002    02/01/2023  Maria Lopez         2000         Ropa
2           T003    2023-01-03    carlos diaz   $-350.00         Ropa
3           T005    2023-01-05            Ana        NaN    Alimentos
4            NaN    2023-01-06           Luis     450.75          NaN
5           T007  invalid_date          Pedro       1000  Electrónica
6           T008    2023-01-08                    800.00    Alimentos

In [22]:
df.isnull()

   id_transaccion  fecha_tx  cliente_nomb  monto_  categoria
0           False     False         False   False      False
1           False     False         False   False      False
2           False     False         False   False      False
3           False     False         False   False      False
4            True     False         False   False       True
5           False     False         False   False      False
6           False     False         False   False      False

In [26]:
df1=df.dropna()
df2=df.dropna(subset=['cliente_nomb'])

In [24]:
df1

  id_transaccion      fecha_tx   cliente_nomb     monto_    categoria
0           T001    2023-01-01     Juan Perez  $1,500.50  Electrónica
1           T002    02/01/2023  Maria Lopez         2000         Ropa
2           T003    2023-01-03    carlos diaz   $-350.00         Ropa
3           T005    2023-01-05            Ana        NaN    Alimentos
5           T007  invalid_date          Pedro       1000  Electrónica
6           T008    2023-01-08                    800.00    Alimentos

In [25]:
df2

  id_transaccion      fecha_tx   cliente_nomb     monto_    categoria
0           T001    2023-01-01     Juan Perez  $1,500.50  Electrónica
1           T002    02/01/2023  Maria Lopez         2000         Ropa
2           T003    2023-01-03    carlos diaz   $-350.00         Ropa
3           T005    2023-01-05            Ana        NaN    Alimentos
5           T007  invalid_date          Pedro       1000  Electrónica
6           T008    2023-01-08                    800.00    Alimentos

In [27]:
df2

  id_transaccion      fecha_tx   cliente_nomb     monto_    categoria
0           T001    2023-01-01     Juan Perez  $1,500.50  Electrónica
1           T002    02/01/2023  Maria Lopez         2000         Ropa
2           T003    2023-01-03    carlos diaz   $-350.00         Ropa
3           T005    2023-01-05            Ana        NaN    Alimentos
4            NaN    2023-01-06           Luis     450.75          NaN
5           T007  invalid_date          Pedro       1000  Electrónica
6           T008    2023-01-08                    800.00    Alimentos

In [28]:
df3=df

In [29]:
df3

  id_transaccion      fecha_tx   cliente_nomb     monto_    categoria
0           T001    2023-01-01     Juan Perez  $1,500.50  Electrónica
1           T002    02/01/2023  Maria Lopez         2000         Ropa
2           T003    2023-01-03    carlos diaz   $-350.00         Ropa
3           T005    2023-01-05            Ana        NaN    Alimentos
4            NaN    2023-01-06           Luis     450.75          NaN
5           T007  invalid_date          Pedro       1000  Electrónica
6           T008    2023-01-08                    800.00    Alimentos

In [31]:
df3=df.copy(deep=True)

In [32]:
df3

  id_transaccion      fecha_tx   cliente_nomb     monto_    categoria
0           T001    2023-01-01     Juan Perez  $1,500.50  Electrónica
1           T002    02/01/2023  Maria Lopez         2000         Ropa
2           T003    2023-01-03    carlos diaz   $-350.00         Ropa
3           T005    2023-01-05            Ana        NaN    Alimentos
4            NaN    2023-01-06           Luis     450.75          NaN
5           T007  invalid_date          Pedro       1000  Electrónica
6           T008    2023-01-08                    800.00    Alimentos

In [33]:
df3.dropna(inplace=True)

In [34]:
df3

  id_transaccion      fecha_tx   cliente_nomb     monto_    categoria
0           T001    2023-01-01     Juan Perez  $1,500.50  Electrónica
1           T002    02/01/2023  Maria Lopez         2000         Ropa
2           T003    2023-01-03    carlos diaz   $-350.00         Ropa
3           T005    2023-01-05            Ana        NaN    Alimentos
5           T007  invalid_date          Pedro       1000  Electrónica
6           T008    2023-01-08                    800.00    Alimentos

In [35]:
print("--- 4. MANEJO DE STRINGS ---")
# Limpiar nombres de clientes: quitar espacios extra y aplicar Title Case (Mayúscula Inicial)
# Se reemplazan también strings vacíos o compuestos solo por espacios a NaN
df['cliente_nomb'] = df['cliente_nomb'].str.strip().str.title()
df['cliente_nomb'] = df['cliente_nomb'].replace('', np.nan)
df['cliente_nomb'] = df['cliente_nomb'].fillna('Cliente Anónimo')

print(df[['id_transaccion', 'cliente_nomb']])
print("\n")

--- 4. MANEJO DE STRINGS ---
  id_transaccion     cliente_nomb
0           T001       Juan Perez
1           T002      Maria Lopez
2           T003      Carlos Diaz
3           T005              Ana
4            NaN             Luis
5           T007            Pedro
6           T008  Cliente Anónimo

In [42]:
print("--- 5. FORMATOS INCORRECTOS Y CONVERSIÓN DE TIPOS ---")

# Limpiar columna de montos (eliminar símbolos de moneda y comas)
df['monto_'] = (
    df['monto_']
    .astype(str)
    .str.replace('$', '', regex=False)
    .str.replace(',', '', regex=False)
    .str.replace('NaN', '0', regex=False) # Manejar el string 'NaN'
)

--- 5. FORMATOS INCORRECTOS Y CONVERSIÓN DE TIPOS ---

In [43]:
df['monto_'] = df['monto_'].astype(float)

In [44]:
df = df.rename(columns={'monto_': 'monto'})

In [45]:
df

  id_transaccion      fecha_tx     cliente_nomb    monto    categoria
0           T001    2023-01-01       Juan Perez  1500.50  Electrónica
1           T002    02/01/2023      Maria Lopez  2000.00         Ropa
2           T003    2023-01-03      Carlos Diaz  -350.00         Ropa
3           T005    2023-01-05              Ana     0.00    Alimentos
4            NaN    2023-01-06             Luis   450.75          NaN
5           T007  invalid_date            Pedro  1000.00  Electrónica
6           T008    2023-01-08  Cliente Anónimo   800.00    Alimentos

In [46]:
df['fecha_tx'] = pd.to_datetime(df['fecha_tx'], errors='coerce')

In [47]:
df

  id_transaccion   fecha_tx     cliente_nomb    monto    categoria
0           T001 2023-01-01       Juan Perez  1500.50  Electrónica
1           T002        NaT      Maria Lopez  2000.00         Ropa
2           T003 2023-01-03      Carlos Diaz  -350.00         Ropa
3           T005 2023-01-05              Ana     0.00    Alimentos
4            NaN 2023-01-06             Luis   450.75          NaN
5           T007        NaT            Pedro  1000.00  Electrónica
6           T008 2023-01-08  Cliente Anónimo   800.00    Alimentos

In [48]:
print(df[['monto', 'fecha_tx']])
print("Nuevos tipos de datos:")
print(df[['monto', 'fecha_tx']].dtypes)
print("\n")

     monto   fecha_tx
0  1500.50 2023-01-01
1  2000.00        NaT
2  -350.00 2023-01-03
3     0.00 2023-01-05
4   450.75 2023-01-06
5  1000.00        NaT
6   800.00 2023-01-08
Nuevos tipos de datos:
monto              float64
fecha_tx    datetime64[ns]
dtype: object

In [49]:
print("--- 6. DETECCIÓN DE INCONSISTENCIAS ---")
# Identificar montos negativos (una regla de negocio podría dictar que no existen montos negativos)
inconsistencias_monto = df[df['monto'] < 0]
print(f"Registros con montos negativos encontrados:\n{inconsistencias_monto}\n")

--- 6. DETECCIÓN DE INCONSISTENCIAS ---
Registros con montos negativos encontrados:
  id_transaccion   fecha_tx cliente_nomb  monto categoria
2           T003 2023-01-03  Carlos Diaz -350.0      Ropa

In [51]:
df['monto']<=0

0    False
1    False
2     True
3     True
4    False
5    False
6    False
Name: monto, dtype: bool

In [52]:
 df[df['monto'] <= 0]

  id_transaccion   fecha_tx cliente_nomb  monto  categoria
2           T003 2023-01-03  Carlos Diaz -350.0       Ropa
3           T005 2023-01-05          Ana    0.0  Alimentos

In [53]:
df['monto'] = df['monto'].abs()

In [54]:
df

  id_transaccion   fecha_tx     cliente_nomb    monto    categoria
0           T001 2023-01-01       Juan Perez  1500.50  Electrónica
1           T002        NaT      Maria Lopez  2000.00         Ropa
2           T003 2023-01-03      Carlos Diaz   350.00         Ropa
3           T005 2023-01-05              Ana     0.00    Alimentos
4            NaN 2023-01-06             Luis   450.75          NaN
5           T007        NaT            Pedro  1000.00  Electrónica
6           T008 2023-01-08  Cliente Anónimo   800.00    Alimentos

In [55]:
df = df.dropna(subset=['fecha_tx']).reset_index(drop=True)

In [56]:
df

  id_transaccion   fecha_tx     cliente_nomb    monto    categoria
0           T001 2023-01-01       Juan Perez  1500.50  Electrónica
1           T003 2023-01-03      Carlos Diaz   350.00         Ropa
2           T005 2023-01-05              Ana     0.00    Alimentos
3            NaN 2023-01-06             Luis   450.75          NaN
4           T008 2023-01-08  Cliente Anónimo   800.00    Alimentos

In [57]:
# =============================================================================
# ST11: Buenas prácticas de limpieza (Resultados Finales)
# =============================================================================
print("--- DATOS FINALES (LIMPIOS) ---")
# Ordenar el dataframe por fecha
df = df.sort_values('fecha_tx').reset_index(drop=True)
print(df)
print("\nResumen final del DataFrame:")
print(df.info())

--- DATOS FINALES (LIMPIOS) ---
  id_transaccion   fecha_tx     cliente_nomb    monto    categoria
0           T001 2023-01-01       Juan Perez  1500.50  Electrónica
1           T003 2023-01-03      Carlos Diaz   350.00         Ropa
2           T005 2023-01-05              Ana     0.00    Alimentos
3            NaN 2023-01-06             Luis   450.75          NaN
4           T008 2023-01-08  Cliente Anónimo   800.00    Alimentos

Resumen final del DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_transaccion  4 non-null      object
 1   fecha_tx        5 non-null      datetime64[ns]
 2   cliente_nomb    5 non-null      object
 3   monto           5 non-null      float64
 4   categoria       4 non-null      object
dtypes: datetime64[ns](1), float64(1), object(3)
memory usage: 332.0+ bytes
None